myshop/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile_form/', views.profile_form, name='profile_form'),
    path('profile/', views.profile, name='profile'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),  # Маршруты из приложения accounts
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

myshop/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)

myshop/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Profile  # Импорт модели профиля пользователя


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'address', 'postal_code', 'city']

myshop/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import ProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Аутентификация и вход в систему пользователя после регистрации
            authenticated_user = authenticate(username=user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return redirect('accounts:profile_form')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def profile_form(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST)
        if profile_form.is_valid() and request.user.is_authenticated:
            profile = profile_form.save(commit=False)  # Сначала создаем профиль, не сохраняя его в базе данных
            profile.user = request.user  # Присваиваем текущего пользователя атрибуту user профиля
            profile.save()  # Сохраняем профиль
            return redirect('shop:product_list')
    else:
        profile_form = ProfileForm()
    return render(request, 'accounts/profile_form.html', {'profile_form': profile_form})


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('accounts:password_change_done')


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'

myshop/accounts/templates/accounts/login.html
{% extends "shop/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="button">Login</button>
  </form>
{% endblock %}

myshop/accounts/templates/accounts/password_change_done.html
{% extends "shop/base.html" %}

{% block title %}Password Changed{% endblock %}

{% block content %}
  <h2>Password Changed</h2>
  <p>Your password has been changed successfully.</p>
  <a href="{% url 'shop:product_list' %}">Return to the homepage</a>
{% endblock %}

myshop/accounts/templates/accounts/password_change_form.html
{% extends "shop/base.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change Password" class="text-link" />
  </form>
{% endblock %}

myshop/accounts/templates/accounts/profile.html
{% extends "shop/base.html" %}

{% block content %}
  <h2>Профиль пользователя</h2>
  <p>Имя пользователя: {{ user.username }}</p>
  <p>Электронная почта: {{ user.email }}</p>
  
  <hr>
  <!-- Ссылка для смены пароля -->
    <a href="{% url 'accounts:password_change' %}">Сменить пароль</a>
{% endblock %}

myshop/accounts/templates/accounts/profile_form.html
{% extends "shop/base.html" %}

{% block title %}Profile Form{% endblock %}

{% block content %}
<h2>Profile Information</h2>
<form method="post">
    {% csrf_token %}
    {{ profile_form.as_p }}
    <button type="submit" class="button">Save</button>
    <a href="{% url 'shop:product_list' %}" class="button">Skip and continue later</a>
</form>
{% endblock %}

myshop/accounts/templates/accounts/register.html
{% extends "shop/base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="button">Register</button>
</form>
{% endblock %}